### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/DSCI_522_group_401#1]
Let's explore various options here and finalize our project.

**Comment by sirine-chahma** [comment]
What do you think about this dataset?
[predicting a pulsar star](https://www.kaggle.com/pavanraj159/predicting-a-pulsar-star )

It's unbalanced but I think there are still enough values and we can still work with it! :)

**Comment by sreejithmunthikodu** [comment]
I liked the dataset although the features are less intuitive without the domain knowledge. But thats a matter of 10-15 mins of reading I guess.

Below are some of the datasets I found.
1. [Loan prediction](https://www.kaggle.com/altruistdelhite04/loan-prediction-problem-dataset)
2. [Insurance premium prediction](https://www.kaggle.com/noordeen/insurance-premium-prediction)
3. [Cardiovascular Disease dataset](https://www.kaggle.com/sulianova/cardiovascular-disease-dataset)

**Comment by singh-karanpal** [comment]
Due to licensing issues, we can't use the above. Please have a look at this:
[Bank Marketing Data](https://archive.ics.uci.edu/ml/datasets/bank+marketing)

This data is available for research and public use.

If you find something interesting just post it here.

**Comment by sreejithmunthikodu** [comment]
It looks good to me.

**Comment by sirine-chahma** [comment]
Another insurance dataset [link](https://gist.github.com/meperezcuello/82a9f1c1c473d6585e750ad2e3c05a41)

**Comment by singh-karanpal** [comment]
The above dataset has been finalized and approved by Firas. 
Now we can split tasks and come up with the research questions.
I will share them soon!


Thanks, Team!

**Comment by sreejithmunthikodu** [comment]
Various research questions that Sirine came up with are:
Research questions :
- Is there a significant difference of expenses between smokers and non-smokers? (inferential)
    We would do a two-side hypothesis test.
- Is there a significant difference of expenses between males and females? (inferential)
    We would do a two-side hypothesis test.
- Is there a relationship between the bmi and the gendre of a person? (inferential)
    We would do a two-side hypothesis test.
- Given a person's information, what would be his/her predicted expenses? (predictive)
    Regression with different models (linear regression, glm,...)

I think we should stick with the last one as our main research question. What do you guys think?

**Comment by sirine-chahma** [comment]
we chose this dataset https://gist.github.com/meperezcuello/82a9f1c1c473d6585e750ad2e3c05a41
