### ISSUE TITLE
Concern: Saving Plots to Image

### ISSUE THREAD

**Issue by singh-karanpal** [UBC-MDS/DSCI_522_group_401#13]
Team,

We have used Altair for EDA, to save these plots to `png` or `svg` it requires one google dependency. I have installed this on local however, we have to take care of this when we are deploying all scripts using Docker or some other container.

We have to maintain a list where we have to list all packages and dependencies.

Regards
Karan

**Comment by sreejithmunthikodu** [comment]
selenium                  3.141.0 
ChromeDriver 79.0.3945.36

**Comment by singh-karanpal** [comment]
It is working for all of us now, so I am going ahead and closing this issue.
