### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/DSCI_522_group_401#15]
Guys, for the report, how about we follow Tiffany's format  (https://github.com/ttimbers/breast_cancer_predictor/blob/master/src/breast_cancer_eda.Rmd) with the following draft sections?
In her report she is creating the plots in the Rmarkdown. I dont think we will have to do it since we are saving those images in the previous scripts.
Please free free to change the sections and reassign
-  Summary of the data set (Sirine)
-  Partition the data set into training and test sets  (Sirine)
-  Exploratory analysis on the training data set (Karan)
-  Answer the inferential research questions  (Karan)
-  Build a predictive model (Sree)
-  Evaluate the predictive model (Sree)
-  References (All cite their respective ref)

**Comment by singh-karanpal** [comment]
Thanks for sharing the template, will be easy to follow along. We will commit changes and do proofreading at the end.

**Comment by sirine-chahma** [comment]
It works for me!
