### ISSUE TITLE
Addressing TA feedback

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/DSCI_522_group_401#16]
Regarding #7, 
1. For the prediction model, we will try different regression models with the default parameters and choose the best one for further hyper-parameter tuning. The models we tried are :
"linear_regression" ,   "decision_tree_regressor" ,   "knn_regression" ,  "rf_regression" RandomForestRegressor,  "SVR" .
This will be updated in the project proposal

**Comment by singh-karanpal** [comment]
That is a small change, Once, you add this detail to README feel free to close this issue :) 
I am happy that overall feedback was positive.

**Comment by singh-karanpal** [comment]
These changes were made so I am going ahead and closing this issue.
