### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by aakanksha023** [UBC-MDS/DSCI_522_group_401#27]
- Intuitively features like 'age', 'BMI', etc. are correlated, So expect a brief discussion on correlation and how that should be handled
- Just a suggestion: Analysis would make sense if the predictors are in intervals. For ex. Age group 0-18 would not have heavy influence of "Smoking" habits and will by default have best BMI values. So a separate analysis would make more sense when predicting insurance price in that age group.

**Comment by sirine-chahma** [comment]
We grouped all the feedbacks in another issue
