### ISSUE TITLE
Final Peer feedbacks

### ISSUE THREAD

**Issue by sirine-chahma** [UBC-MDS/DSCI_522_group_401#30]
- feature importance plot (lollipop chart for example) (Sree)
- check the correlation between features (for example correlation heatmap,...) (Sirine)
- remove the BMI VS age plot (Sirine)
- split the BMI in 3 categories and treate it as a categorical variable (Sirine)
- do a one side hypothesis test for the smoker VS non-smoker test (Karan)
- add the line y=x on the actual VS predicted expenses (Sree)

**Comment by sirine-chahma** [comment]
The correlation heatmap is done

**Comment by sirine-chahma** [comment]
I removed the BMI VS age plot

**Comment by sirine-chahma** [comment]
I split the BMI in 4 categories and updated the corresponding charts

**Comment by singh-karanpal** [comment]
I have updated following to the project:

- Makefile workflow
- One Side Hypothesis Test
- Added Test Case to EDA

**Comment by singh-karanpal** [comment]
We have addressed all of the above concerns in our Milestone 3. At this point in time, we have addressed TA feedbacks and Peer feedbacks too. We can close this issue now.
