### ISSUE TITLE
Milestone 2 Feedback: Minor

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_group_401#34]
- [x] Beautiful and relevant visualizations, well done! Some minor formatting is required such as increasing text size.

- [x] Please proofread your report and main README. There were some typos and grammar mistakes.

**Comment by singh-karanpal** [comment]
Thanks a lot, @Nazliozum for such constructive and motivational feedback. 


**Addressing your feedback**

We have tried our best to re-format our plots as per your feedback and we have done proofreading and we have tried to correct our sentences as much as possible. Also, we have run our narrative through the English Language tool just-in-case we have missed something.

So, I am going ahead and closing this issue.
