### ISSUE TITLE
Missing tests in code

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/DSCI_522_group_401#38]
As per TA feedback #32

**Comment by sreejithmunthikodu** [comment]
- Included tests in data download script
- Tests included for all functions in predictive modeling script

**Comment by singh-karanpal** [comment]
- Tests included in Exploratory Data Analysis Script
- Inferences script already had tests included

**Comment by singh-karanpal** [comment]
As it was required we have added test cases to:

- Download Script
- EDA Script
- Inferential Analysis (already had the test cases)
- Predictive  Modelling Script

So, I am going ahead and closing this issue.
