### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_group_401#47]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] It would really have helped if you had a caption and a figure/table number for each plot. That way you can easily reference it in your text, and it's easier for readers to find
- - [x] Great job formatting all y-axis labels with thousands separator
- - [x] You should rotate all x-axis labels so they're oriented correctly: `alt.X('Var:N', axis=alt.Axis(labelAngle=0))`
- - [x] There's a spelling mistake in Medical expenses vs BMI (underweight)
- - [x] You [sort](https://github.com/altair-viz/altair/issues/1137#issuecomment-458236850) x-axis categorical labels in increasing order (obese should be at the end)
- - [x] Legend order of Smokers vs. Non Smokers [should be switched](https://github.com/altair-viz/altair/issues/1059#issuecomment-408950717) so first is orange, then blue
- - [x] Not sure if stacked bar chart is appropriate for the Male & female expenses over BMI. Consider a [grouped bar chart](https://altair-viz.github.io/gallery/grouped_bar_chart_horizontal.html), you should decide if horizontal or vertical is more appropriate for your case
- - [x] Consider setting diagonal values on your correlation map to be 0 or nan; those are the only ones that stand out.
- - [x] Ideally, you only want to show half the correlation map as the other half is redundant (see example [here](http://www.sthda.com/sthda/RDoc/figure/ggplot2/ggplot2-correlation-matrix-heatmap-add-correlation-coefficients-1.png)) - let me know if you figure out how to do this in Altair
- - [ ] You've got overplotting happening in your goodness of fit plots - is jttering appropriate here?
- - [x] Overall excellent work with your labels, titles, and plot choices! For every plot I was immediately able to understand what you were trying to convey.

**Comment by sirine-chahma** [comment]
Thank you very much for you feedbacks!

**Comment by sreejithmunthikodu** [comment]
Thanks, Firas for such detailed visualization feedback. 
- For the overplotting in the goodness of fit, we feel jittering is not appropriate. This is because jittering needs at least one categoric variable (`Jittering is particularly useful for small datasets with at least one discrete position.` https://ggplot2.tidyverse.org/reference/position_jitter.html). 
- We tried to address this issue by lowering the opacity.

**Comment by firasm** [comment]
Thanks @sreejithmunthikodu - did you figure out what was causing your plots to look like they were discrete? I saw bands when I was talking to @sirine-chahma about it yesterday. Could you just paste the final figure here so I can have a quick look?

**Comment by sreejithmunthikodu** [comment]
Hi @firasm, we used a DecisionTreeRegressor with a max_depth of 4. So I guess there are 16 leaf nodes. So any sample would end up in one of these 16 leaf nodes and the final output would be the mean value from all the samples in these leaf nodes. So even though our response is continuous, our models is capable of predicting only 16 closest values. Now I feel jitter may be used here.
Do you recommend it?
Thanks

**Comment by firasm** [comment]
Can you post the jitter'd and non-jittered plot here?

**Comment by sreejithmunthikodu** [comment]
Hi @firasm,
Below is what I managed to get so far. 

![visualization (1)](https://user-images.githubusercontent.com/37257063/73985837-141d3c80-48f1-11ea-89a8-147064490c0b.png)

**Comment by sreejithmunthikodu** [comment]
The x variable is now treated as categorical. But I lost the spacing between the values now. All are equally spaced. I tried to change the type to "Q" but still the same result.

I am sure there has to be a way to do it properly. I am searching for it online. 

Below is my original plot.

**Comment by sreejithmunthikodu** [comment]
![predicted_vs_actual_plot](https://user-images.githubusercontent.com/37257063/73986060-93ab0b80-48f1-11ea-9e75-f976b5cb4985.png)

**Comment by sreejithmunthikodu** [comment]
Here is the code I used

`alt.Chart(res).mark_circle(size=60, color="green", opacity=0.4).encode(
    alt.X("jitter:Q", 
          title = None,
          axis=alt.Axis(values=[0], ticks=True, grid=False, labels=False),
          scale=alt.Scale()),         
    alt.Y('y_actual', title = "Actual Medical Expense ($)"),
    alt.Column(
        'y_predicted:Q',
         title = "Predicted Medical Expense ($)",

         header=alt.Header(
             labelAngle=-90,
             titleOrient='top',
             labelOrient='bottom',
             labelAlign='right',
             labelPadding=0,
             labelFontSize=20,
             title = "Predicted Vs Actual",
             titleFontSize=20,)
    ),
    ).transform_calculate(   
    jitter='sqrt(-2*log(random()))*cos(2*PI*random())/1000'
    ).configure_facet(
    spacing=0
    ).configure_view(
    stroke=None
    ).properties(    
    width = 40,
    height = 400
    ).configure_axis(
    labelFontSize = 20,
    titleFontSize = 20
    ).configure_title(
    fontSize = 20
    ).configure_legend(
    titleFontSize = 20, labelFontSize = 20)`

**Comment by sreejithmunthikodu** [comment]
`alt.Chart(res).mark_circle(size=60, color="green", opacity=0.4).encode(
    alt.X("jitter:Q", 
          title = None,
          axis=alt.Axis(values=[0], ticks=True, grid=False, labels=False),
          scale=alt.Scale()),         
    alt.Y('y_actual', title = "Actual Medical Expense ($)"),
    alt.Column(
        'y_predicted:Q',
         title = "Predicted Medical Expense ($)",

         header=alt.Header(
             labelAngle=-90,
             titleOrient='top',
             labelOrient='bottom',
             labelAlign='right',
             labelPadding=0,
             labelFontSize=20,
             title = "Predicted Vs Actual",
             titleFontSize=20,)
    ),
    ).transform_calculate(   
    jitter='sqrt(-2*log(random()))*cos(2*PI*random())/1000'
    ).configure_facet(
    spacing=0
    ).configure_view(
    stroke=None
    ).properties(    
    width = 40,
    height = 400
    ).configure_axis(
    labelFontSize = 20,
    titleFontSize = 20
    ).configure_title(
    fontSize = 20
    ).configure_legend(
    titleFontSize = 20, labelFontSize = 20)`

**Comment by sreejithmunthikodu** [comment]
`alt.Chart(res).mark_circle(size=60, color="green", opacity=0.4).encode(
    alt.X("jitter:Q", 
          title = None,
          axis=alt.Axis(values=[0], ticks=True, grid=False, labels=False),
          scale=alt.Scale()),         
    alt.Y('y_actual', title = "Actual Medical Expense ($)"),
    alt.Column(
        'y_predicted:Q',
         title = "Predicted Medical Expense ($)",
         header=alt.Header(
             labelAngle=-90,
             titleOrient='top',
             labelOrient='bottom',
             labelAlign='right',
             labelPadding=0,
             labelFontSize=20,
             title = "Predicted Vs Actual",
             titleFontSize=20,)
    ),
    ).transform_calculate(   
    jitter='sqrt(-2*log(random()))*cos(2*PI*random())/1000'
    ).configure_facet(
    spacing=0
    ).configure_view(
    stroke=None
    ).properties(    
    width = 40,
    height = 400
    ).configure_axis(
    labelFontSize = 20,
    titleFontSize = 20
    ).configure_title(
    fontSize = 20
    ).configure_legend(
    titleFontSize = 20, labelFontSize = 20)`

**Comment by sreejithmunthikodu** [comment]
Here is the code I used.
`alt.Chart(res).mark_circle(size=60, color="green", opacity=0.4).encode(
    alt.X("jitter:Q", 
          title = None,
          axis=alt.Axis(values=[0], ticks=True, grid=False, labels=False),
          scale=alt.Scale()),         
    alt.Y('y_actual', title = "Actual Medical Expense ($)"),

    alt.Column(
        'y_predicted:Q',
         title = "Predicted Medical Expense ($)",
         header=alt.Header(
             labelAngle=-90,
             titleOrient='top',
             labelOrient='bottom',
             labelAlign='right',
             labelPadding=0,
             labelFontSize=20,
             title = "Predicted Vs Actual",
             titleFontSize=20,)
    ),
    ).transform_calculate(   
    jitter='sqrt(-2*log(random()))*cos(2*PI*random())/1000'
    ).configure_facet(
    spacing=0
    ).configure_view(
    stroke=None
    ).properties(    
    width = 40,
    height = 400
    ).configure_axis(
    labelFontSize = 20,
    titleFontSize = 20
    ).configure_title(
    fontSize = 20
    ).configure_legend(
    titleFontSize = 20, labelFontSize = 20)`

**Comment by sreejithmunthikodu** [comment]
We addressed all the issues except one mentioned here. We could not resolve the overplotting issue in the goodness of fit plots with jittering. Because of our decision tree model, the predicted values behave like a categorical variable. However, when jittering was used, the predicted values takes equal intervals in the x-axis. 

Thanks, Firas for your valuable feedback. It really helped us to improve a lot.

**Comment by firasm** [comment]
Sounds great, thanks for considering!

**Comment by firasm** [comment]
Sorry I didn't get a chance to look at this in time
