### ISSUE TITLE
Milestone 3 Feedback: Reasoning

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_group_401#49]
- [x] There is conflicting information in the "Summary" section and "Answering the Inferential Research Questions" section regarding the difference between males' and females' medical expenses.

- [x] Expand on your discussion of the chosen predictive model. Even though you present mean error values in the table, it is better practice to interpret the results within the textual explanations of your report.

**Comment by sreejithmunthikodu** [comment]
Following issues are addressed in #54 
1. Added more information on the chosen predictive model. 
2. Included interpretation of the results in the report

**Comment by sreejithmunthikodu** [comment]
Both the issues mentioned here are resolved.
