### ISSUE TITLE
Milestone 3 Feedback: Viz

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_group_401#50]
I think the visualizations are very clear and there is amazing improvement compared to Milestone 2! Here are some improvement points:

- [x] Switch the x and y axis data in Figures 2 and 5 so the categories are on the y axis and expenses are on the x axis.
- [x] Add the BMI intervals in the labels of BMI categories on figures. For example, when you refer to "people from both genders who have a BMI that is higher than 34" in the report, I cannot see which category that falls into. Either mention the category in the report text or add the intervals on the graphs.

**Comment by sirine-chahma** [comment]
I added a paragraph at the beginning of the EDA explaining the corresponding BMI for each category.
