### ISSUE TITLE
Milestone 1 preliminary feedback

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/DSCI_522_group_401#7]
- Your analysis plan and data look fine. 
- Be more specific in your analysis plan (Will you use only those 3 models or more? Which specific "relevant metrics" will you use to present the results?)

**Comment by singh-karanpal** [comment]
Regarding being specific in mentioning models we were comparing, we have addressed TA's feedback in Milestone 2 we can go ahead and close this issue.
