### ISSUE TITLE
Data analysis pipeline

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/DSCI_522_group_401#9]
Guys,
since our major research question is a predictive task, in script 4, as discussed, let's build the machine learning model. I am not very sure where our other research questions fit in and how to include those in script 4. What do you guys suggest?

Since the sub-questions are about hypothesis testing, I guess we should do them in R. But the predictive model is in Python. Should we have one more script in R?

Or should we just go ahead with our main research question for this milestone?

**Comment by sirine-chahma** [comment]
I think it could still be useful to try to answer the sub-questions. I don't see any issue in doing an R file for the inferential questions, and running the main prediction analysis in a Python file

**Comment by singh-karanpal** [comment]
Yes, I will take this task and do it in R. Also, for this milestone we have to create at least 1 script in R. @sirine-chahma has already created one and I will create another one.
